name: example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor_flutter: ^1.7.0
  clustering_google_maps:
      path: ../
  cupertino_icons: ^0.1.2
  tesla: ^0.2.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.0
  json_serializable: ^3.0.0
  moor_generator: ^1.5.0

flutter:

  uses-material-design: true

  assets:
    - assets/map_point.json


dependency_overrides:
  tesla:
    git: "https://github.com/AppleEducate/tesla.dart"